/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.controlador;
import Modelo.Personaje;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class jDialogMostrarPersonajes extends javax.swing.JDialog {
    controlador c = new controlador();
    private ArrayList<Personaje> lista;
    private Personaje pActual;
    /**
     * Creates new form jDialogMostrarPersonajes
     */
    public jDialogMostrarPersonajes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanelPrincipal.setVisible(false);
        //Ya tengo los personajes en la lista
        
        actualizarPersonajes();
        

        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPersonajes = new javax.swing.JList<>();
        jButtonCrear = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelArmadura = new javax.swing.JPanel();
        jSpinnerArmadura = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldClase = new javax.swing.JTextField();
        jPanelVida = new javax.swing.JPanel();
        jSpinnerVida = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanelMana = new javax.swing.JPanel();
        jSpinnerMana = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jPaneDanyo = new javax.swing.JPanel();
        jSpinnerDanyo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jPanelDinero = new javax.swing.JPanel();
        jSpinnerDinero = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonBorrarSeleccion = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jListPersonajes);

        jButtonCrear.setText("CREAR");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonSeleccionar.setText("SELECCIONAR");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });

        jPanelArmadura.setBackground(new java.awt.Color(205, 205, 205));
        jPanelArmadura.setPreferredSize(new java.awt.Dimension(265, 39));

        jLabel4.setText("Puntos Armadura:");

        javax.swing.GroupLayout jPanelArmaduraLayout = new javax.swing.GroupLayout(jPanelArmadura);
        jPanelArmadura.setLayout(jPanelArmaduraLayout);
        jPanelArmaduraLayout.setHorizontalGroup(
            jPanelArmaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArmaduraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jSpinnerArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelArmaduraLayout.setVerticalGroup(
            jPanelArmaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSpinnerArmadura, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Clase:");

        jPanelVida.setBackground(new java.awt.Color(255, 35, 0));
        jPanelVida.setPreferredSize(new java.awt.Dimension(265, 39));

        jLabel3.setText("Puntos Vida:");

        javax.swing.GroupLayout jPanelVidaLayout = new javax.swing.GroupLayout(jPanelVida);
        jPanelVida.setLayout(jPanelVidaLayout);
        jPanelVidaLayout.setHorizontalGroup(
            jPanelVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVidaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinnerVida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelVidaLayout.setVerticalGroup(
            jPanelVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSpinnerVida, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanelMana.setBackground(new java.awt.Color(59, 131, 189));

        jLabel8.setBackground(new java.awt.Color(59, 131, 189));
        jLabel8.setText("Puntos Mana:");

        javax.swing.GroupLayout jPanelManaLayout = new javax.swing.GroupLayout(jPanelMana);
        jPanelMana.setLayout(jPanelManaLayout);
        jPanelManaLayout.setHorizontalGroup(
            jPanelManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jSpinnerMana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelManaLayout.setVerticalGroup(
            jPanelManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSpinnerMana, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPaneDanyo.setBackground(new java.awt.Color(0, 255, 51));
        jPaneDanyo.setPreferredSize(new java.awt.Dimension(265, 39));

        jLabel5.setText("Puntos Daño:");

        javax.swing.GroupLayout jPaneDanyoLayout = new javax.swing.GroupLayout(jPaneDanyo);
        jPaneDanyo.setLayout(jPaneDanyoLayout);
        jPaneDanyoLayout.setHorizontalGroup(
            jPaneDanyoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneDanyoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jSpinnerDanyo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneDanyoLayout.setVerticalGroup(
            jPaneDanyoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSpinnerDanyo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanelDinero.setBackground(new java.awt.Color(239, 164, 16));
        jPanelDinero.setPreferredSize(new java.awt.Dimension(265, 39));

        jLabel6.setText("Monedas Oro: ");

        javax.swing.GroupLayout jPanelDineroLayout = new javax.swing.GroupLayout(jPanelDinero);
        jPanelDinero.setLayout(jPanelDineroLayout);
        jPanelDineroLayout.setHorizontalGroup(
            jPanelDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDineroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jSpinnerDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDineroLayout.setVerticalGroup(
            jPanelDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSpinnerDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jButton1.setText("Objetos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldClase)
                        .addContainerGap())
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanelVida, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addComponent(jPanelDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(jPanelMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jPanelArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(289, Short.MAX_VALUE)))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addComponent(jPaneDanyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jPanelVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBorrar)
                        .addComponent(jButtonValidar)))
                .addContainerGap())
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jPanelMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jPanelArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(jPaneDanyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jButtonBorrarSeleccion.setText("BORRAR SELECIONADO");
        jButtonBorrarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarSeleccionActionPerformed(evt);
            }
        });

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBorrarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonBorrarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed

        if(jButtonSeleccionar.getText()=="SELECCIONAR"){
            try{

                int index = jListPersonajes.getSelectedIndex();

                Personaje p = lista.get(index);
                pActual = p;
                jPanelPrincipal.setVisible(true);


                
                
                
                jTextFieldNombre.setEditable(false);
                jTextFieldClase.setEditable(false);
                jTextFieldNombre.setText(p.getNombre());
                jTextFieldClase.setText(p.getClase());
                jSpinnerVida.setValue(p.getPuntosvida());
                jSpinnerMana.setValue(p.getPuntosmana());
                jSpinnerArmadura.setValue(p.getPuntosarmadura());
                jSpinnerDanyo.setValue(p.getPuntosdanyo());
                jSpinnerDinero.setValue(p.getDinero());

                JOptionPane.showMessageDialog(null, "Ya puede comenzar su partida");
                jButtonValidar.setEnabled(false);
                jButtonBorrar.setEnabled(false);
                jButtonCrear.setEnabled(false);
                jButtonBorrarSeleccion.setEnabled(false);
                jButtonSeleccionar.setText("GUARDAR CAMBIOS");
            }catch(ArrayIndexOutOfBoundsException e){
                e.printStackTrace(System.err);
                JOptionPane.showMessageDialog(null, "Seleccione un personaje!");
            }
        }else{
            
            int idPer = pActual.getId();
            
            String nombre = jTextFieldNombre.getText();
            String clase = jTextFieldClase.getText();
            int pv = (int)jSpinnerVida.getValue();
            int pm = (int)jSpinnerMana.getValue();
            int pa = (int)jSpinnerArmadura.getValue();
            int pd = (int)jSpinnerDanyo.getValue();
            int d = (int)jSpinnerDinero.getValue();
            
            Personaje per = new Personaje(idPer, nombre, clase, pv, pm, pa, pd, d);
            
            boolean todoOk = c.actualizarPerosnaje(per);
            
            if(todoOk){
                JOptionPane.showMessageDialog(null, "Actualizado!");
                    jTextFieldNombre.setText("");
                    jTextFieldClase.setText("");
                    jSpinnerVida.setValue(0);
                    jSpinnerMana.setValue(0);
                    jSpinnerArmadura.setValue(0);
                    jSpinnerDanyo.setValue(0);
                    jSpinnerDinero.setValue(0);
                    jButtonSeleccionar.setText("SELECCIONAR");
                    jButtonCrear.setEnabled(true);
                    jButtonBorrarSeleccion.setEnabled(true);
            }else
                JOptionPane.showMessageDialog(null, "Algo ha salido mal");
                
        }
        

    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        jPanelPrincipal.setVisible(true);
        jListPersonajes.setEnabled(false);
        jButtonValidar.setEnabled(true);
        jButtonBorrar.setEnabled(true);
        //-----
        jTextFieldNombre.setEditable(true);
        jTextFieldClase.setEditable(true);
        jButtonBorrarSeleccion.setEnabled(false);
        jButtonSeleccionar.setEnabled(false);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombre.getText();
        String clase = jTextFieldClase.getText();
        int pv = (int)jSpinnerVida.getValue();
        int pm = (int)jSpinnerMana.getValue();
        int pa = (int)jSpinnerArmadura.getValue();
        int pd = (int)jSpinnerDanyo.getValue();
        int d = (int)jSpinnerDinero.getValue();
        
        Personaje p = new Personaje(nombre, clase, pv, pm, pa, pd, d);
        if(nombre.length()==0 || clase.length()==0 || pv==0){
            JOptionPane.showMessageDialog(null, "Hay atributos vacíos");
        }else{
            boolean todook = c.insertarPersonaje(p);
            if(todook){
                actualizarPersonajes();   
                jPanelPrincipal.setVisible(false);
                jListPersonajes.setEnabled(true);
                jButtonBorrarSeleccion.setEnabled(true);
                jButtonSeleccionar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        
        jTextFieldNombre.setText("");
        jTextFieldClase.setText("");
        jSpinnerVida.setValue(0);
        jSpinnerMana.setValue(0);
        jSpinnerArmadura.setValue(0);
        jSpinnerDanyo.setValue(0);
        jSpinnerDinero.setValue(0);
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonBorrarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarSeleccionActionPerformed
        try{
            
            int index = jListPersonajes.getSelectedIndex();

            Personaje p = lista.get(index);
            int id = p.getId();

            boolean todook = c.eliminarPersonaje(id);

            p = lista.remove(index);


            JOptionPane.showMessageDialog(null, "Has a eliminado a " + p.getNombre());
        
            actualizarPersonajes();
        }catch(ArrayIndexOutOfBoundsException e){
            e.printStackTrace(System.err);
            JOptionPane.showMessageDialog(null, "Seleccione un personaje!");
        }
    }//GEN-LAST:event_jButtonBorrarSeleccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialogObjetos a = new jDialogObjetos(null, true, pActual);
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        inicio a = new inicio();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarSeleccion;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListPersonajes;
    private javax.swing.JPanel jPaneDanyo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelArmadura;
    private javax.swing.JPanel jPanelDinero;
    private javax.swing.JPanel jPanelMana;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerArmadura;
    private javax.swing.JSpinner jSpinnerDanyo;
    private javax.swing.JSpinner jSpinnerDinero;
    private javax.swing.JSpinner jSpinnerMana;
    private javax.swing.JSpinner jSpinnerVida;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldClase;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void actualizarPersonajes() {
        DefaultListModel listaList = new DefaultListModel();
        jListPersonajes.setModel(listaList);
        lista = c.buscarPersonajes();
        for(int i=0;i<lista.size();i++){

            Personaje p = lista.get(i);           
            String frase = p.getNombre() + "-" +  p.getClase();
            listaList.addElement(frase);
        }
    }
}
